[package]
name = "only-one"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
thiserror = "2.0.17"

[lints.rust]
missing_docs = "warn"

[lints.clippy]
correctness = "warn"
suspicious = "warn"
style = "warn"
complexity = "warn"
perf = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "warn"

missing_errors_doc = { level = "allow", priority = 1 }
